# Deploy prebuilt files to GitHub Pages
name: Deploy Prebuilt Files to GitHub Pages

on:
  # Runs on pushes to the default branch
  push:
    branches: ["master"]

  # Allows you to trigger the workflow manually
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Upload Prebuilt Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build   # Specify the prebuilt folder to upload (your "build" folder)

  # Deployment Job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
